### ISSUE TITLE
bug: vector allocation fails because of short sequences

### ISSUE THREAD

**Issue by meiermark** [soedinglab/BaMMmotif2#13]
command call:
BaMMmotif ./mcf7_GATA_narrow /home/mmeier/git/PEnG-motif/scripts/mcf7_GATA_narrow/mcf7_GATA_narrow.fasta --PWMFile /home/mmeier/git/PEnG-motif/scripts/mcf7_GATA_narrow/mcf7_GATA_narrow.tmp.out --FDR --savePvalues -K 2 --zoops

Result:
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append

Backtrace with gdb:
#10 Motif::initFromPWM (this=0x51546f0, PWM=PWM@entry=0x66b680, asize=4, count=<optimized out>) at /home/mmeier/git/bamm-private/src/bamm/Motif.cpp:255

when printing LW1:
LW1 = -7

There seems to be a very short sequence in the dataset:
>chr8:93080412-93080414
AC

Can you catch this?

**Comment by WanwanGe** [comment]
Fixed!
